name: Release

on:
  push:
    tags:
    - '**'

# remove comments if a recent tag push should
# terminate the older running action
#concurrency:
#  group: ${{ github.ref }}
#  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
